# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gda-cruz <gda-cruz@student.42lisboa.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/10 23:25:19 by gda-cruz          #+#    #+#              #
#    Updated: 2022/12/21 00:46:23 by gda-cruz         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RM				= rm -fr

NAME			= libft.a
INC_DIR			= inc

SRC			=	srcs/ft_atoi.c srcs/ft_bzero.c srcs/ft_calloc.c srcs/ft_isalnum.c \
				srcs/ft_isalpha.c srcs/ft_isascii.c srcs/ft_isdigit.c \
				srcs/ft_isprint.c srcs/ft_itoa.c srcs/ft_striteri.c	srcs/ft_memchr.c \
				srcs/ft_memcmp.c srcs/ft_memcpy.c srcs/ft_memmove.c srcs/ft_memset.c \
				srcs/ft_putchar_fd.c srcs/ft_putendl_fd.c srcs/ft_putstr_fd.c \
				srcs/ft_split.c srcs/ft_strchr.c srcs/ft_strdup.c srcs/ft_strjoin.c \
				srcs/ft_strlcat.c srcs/ft_strlcpy.c srcs/ft_strlen.c srcs/ft_strmapi.c \
				srcs/ft_strncmp.c srcs/ft_strnstr.c srcs/ft_strrchr.c srcs/ft_strtrim.c \
				srcs/ft_substr.c srcs/ft_tolower.c srcs/ft_toupper.c srcs/ft_putnbr_fd.c \
				srcs/ft_lstadd_back.c srcs/ft_lstadd_front.c srcs/ft_lstclear.c \
				srcs/ft_lstdelone.c srcs/ft_lstiter.c srcs/ft_lstlast.c srcs/ft_lstmap.c \
				srcs/ft_lstnew.c srcs/ft_lstsize.c \
				srcs/get_next_line.c \
				srcs/ft_print_c.c srcs/ft_print_d.c srcs/ft_print_i.c srcs/ft_print_p.c \
				srcs/ft_print_s.c srcs/ft_print_u.c srcs/ft_print_x.c srcs/ft_print_X.c \
				srcs/ft_printf.c srcs/ft_redirect.c srcs/ft_flags_bonus.c

OBJ				= $(SRC:srcs/%.c=$(OBJ_DIR)/%.o)
OBJ_DIR			= objects

CC				= gcc
CFLAGS			= -Wall -Wextra -Werror -I$(INC_DIR)

all:			$(NAME)

$(NAME):		$(OBJ) | $(OBJ_DIR)
	@ar -rcs $(NAME) $(OBJ)
	@ranlib $(NAME)

$(OBJ_DIR)/%.o:	srcs/%.c | BUILD_DIR
	@$(CC) $(CFLAGS) -c $(^) -o $(@)

BUILD_DIR:
	@mkdir -p $(OBJ_DIR)

clean:
	@$(RM) $(OBJ_DIR)

fclean:			clean
	@$(RM) $(NAME) $(OBJ_DIR)

re:				fclean all

.PHONY:			all clean fclean re
